In [ ]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [ ]:
## your code

np_array_2 = np.ones(20) * 2
np_arange = np.arange(1, 21)

answer = np_array_2 ** np_arange / np_arange

answer

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [ ]:
## your code

arr_01 = np.ones(5) * 0.1
arr_02 = np.ones(5) * 0.1

np_arr_3 = np.arange(1, 6) * 3
np_arr_4 = np.arange(1, 6) * 4

answer = sum((arr_01 ** np_arr_3) * (arr_02 ** np_arr_4))

print(f'Сумма равна: {answer}')

Сумма равна: 1.0000001000000105e-07


**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [ ]:
## your code

arr_ones = np.ones((8, 8))
np_arr = np.arange(1, 9) % 2

answer = ((arr_ones * np_arr).T + np_arr) % 2
answer

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [ ]:
X = np.random.random((5, 2))

## your code

def to_polar(X):
    rho = (X[0] ** 2 + X[1] ** 2) ** 0.5
    theta = X[1] / X[0]
    return rho, theta

to_polar(X.T)



(array([0.44582705, 0.49554218, 0.58471257, 1.12040065, 0.70085002]),
 array([1.7058401 , 4.25404467, 1.45174331, 1.72409468, 3.51637326]))

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [ ]:
X = np.random.random((10, 10))

## your code
def find_indexes(X):
    max_el = np.argmax(X)
    x, y = max_el // 10, max_el % 10
    return x, y

x, y = find_indexes(X)
print(f'Максимальный элемент находится на пересечении строки {x} и столбца {y}')
# отметим, что нумерация столбцов и строк происходит с нуля

Максимальный элемент находится на пересечении строки 0 и столбца 8


**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [ ]:
from inspect import findsource
X = np.random.random((10, 2))
y = np.random.random((1, 2))

print(X)
print(y)

## your code

def find_nearest(X, y):
    p = sum(((X - y)**2).T)**0.5
    index = np.argmax(p)
    return X[index], index

point, index = find_nearest(X, y)

print(f'\nБлижайшая точка к {y} - это {point} с индексом {index}')

[[0.86033396 0.37321826]
 [0.12026849 0.16715378]
 [0.99826688 0.91245245]
 [0.02266544 0.3537549 ]
 [0.83219504 0.36827288]
 [0.35587439 0.28475045]
 [0.55392492 0.54558362]
 [0.24814944 0.39371919]
 [0.34666685 0.9220949 ]
 [0.37609017 0.83747703]]
[[0.29614753 0.99999515]]

Ближайшая точка к [[0.29614753 0.99999515]] - это [0.12026849 0.16715378] с индексом 1


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [ ]:
## your code
np_arr = np.arange(-3, 3, 0.1)

def func(x):
    if x < 0:
        return x**2 + 2*x + 6
    elif x <= 2:
        return x + 6
    else:
        return x**2 + 4*x - 4


vect_func = np.vectorize(func)

answer = vect_func(np_arr)

answer

array([ 9.  ,  8.61,  8.24,  7.89,  7.56,  7.25,  6.96,  6.69,  6.44,
        6.21,  6.  ,  5.81,  5.64,  5.49,  5.36,  5.25,  5.16,  5.09,
        5.04,  5.01,  5.  ,  5.01,  5.04,  5.09,  5.16,  5.25,  5.36,
        5.49,  5.64,  5.81,  6.  ,  6.1 ,  6.2 ,  6.3 ,  6.4 ,  6.5 ,
        6.6 ,  6.7 ,  6.8 ,  6.9 ,  7.  ,  7.1 ,  7.2 ,  7.3 ,  7.4 ,
        7.5 ,  7.6 ,  7.7 ,  7.8 ,  7.9 ,  8.  ,  8.81,  9.64, 10.49,
       11.36, 12.25, 13.16, 14.09, 15.04, 16.01])

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [23]:
X = np.random.random((10, 10))

# print(X)

## your code
m = np.expand_dims(np.mean(X, axis=1), 1)
# print(f'Среднее: {m}')
print(np.mean(X - m, axis=1))

[ 1.66533454e-17 -1.11022302e-17  2.22044605e-17 -1.11022302e-17
 -1.11022302e-17  1.11022302e-17  2.22044605e-17 -2.22044605e-17
 -1.11022302e-17  2.22044605e-17]


**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [24]:
X = np.random.normal(loc=5, scale=2., size=1000)
variance = np.var(X)
m = np.mean(X)
print(f'Выборочная дисперсия: {variance}\nВыборочное среднее: {m}')

Выборочная дисперсия: 3.9844987633297113
Выборочное среднее: 4.945852540344217


 Надо вспомнить, что это, чтобы проверить

**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [25]:
## your code
# arr_zeros = np.zeros((5, 5))
arr = (np.reshape(np.arange(25), (5, 5)) + np.reshape(np.arange(5), (5, 1))) % 5

arr

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [29]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 0, 3, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [30]:
## your code
def sample(x, c):
    n = len(x)
    assert n > 0
    
    s = np.sum(x)
    vals = s * np.random.rand(c, 1)
    # X = np.repeat([x], 4, axis = 0)
    sums = np.asarray(x) @ np.triu(np.ones((n, n)))
    sums = np.repeat([sums], c, axis = 0)

    print(sums)

    print(vals)
    
    return list(np.sum(sums < vals, axis=1))

            
sample([50, 3, 1, 7, 20], 5)    

[[50. 53. 54. 61. 81.]
 [50. 53. 54. 61. 81.]
 [50. 53. 54. 61. 81.]
 [50. 53. 54. 61. 81.]
 [50. 53. 54. 61. 81.]]
[[45.73219669]
 [47.50706786]
 [70.92571267]
 [25.44407178]
 [30.3572889 ]]


[0, 0, 4, 0, 0]